#pragma once

#include "common.h"	

enum ConsoleColor {
    BLACK = 0,
    BLUE = FOREGROUND_BLUE,
    GREEN = FOREGROUND_GREEN,
    CYAN = FOREGROUND_BLUE | FOREGROUND_GREEN,
    RED = FOREGROUND_RED,
    MAGENTA = FOREGROUND_RED | FOREGROUND_BLUE,
    YELLOW = FOREGROUND_RED | FOREGROUND_GREEN,
    WHITE = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
    INTENSITY = FOREGROUND_INTENSITY, // For brighter colors

    // Background colors
    BG_BLUE = BACKGROUND_BLUE,
    BG_GREEN = BACKGROUND_GREEN,
    BG_CYAN = BACKGROUND_BLUE | BACKGROUND_GREEN,
    BG_RED = BACKGROUND_RED,
    BG_MAGENTA = BACKGROUND_RED | BACKGROUND_BLUE,
    BG_YELLOW = BACKGROUND_RED | BACKGROUND_GREEN,
    BG_WHITE = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE,
    BG_INTENSITY = BACKGROUND_INTENSITY
};

void setTextColor(WORD attributes);
void resetTextColor();